default:
  # put all the required where filters here
  where:
    # examples (you should make sure these filters are valid):
    # - table: course
    #   field: Name
    #   operator: REGEXP
    #   values: .*
    # - table: content
    #   field: Name
    # # operator of `=` or `IN` can be neglected
    #   values:
    #   - 萤火虫
    #   - 超级秒表
